### ISSUE TITLE
Comparing Apples and Oranges

### ISSUE THREAD

**Issue by Danny-Engelman** [jhuddle/ponys#1]
Like many others you come up with bloated JS code a 10 year old would write:
(your example code doesn't even work BTW)

````javascript
const templateString = `
  Hello, <slot>world</slot>!
`;
const templateElement = document.createElement('template');
templateElement.innerHTML = templateString;

class HelloWorld extends HTMLElement {

  constructor() {
    let content = templateElement.content.cloneNode(true);
    let shadowRoot = this.attachShadow({mode: 'open'});
    shadowRoot.append(content);
  }

}

customElements.define('hello-world', HelloWorld);```
````

**where a developer that had some education would write:**

````javascript
customElements.define('hello-world', class extends HTMLElement {
  constructor() {
    super().attachShadow({mode:'open'}).innerHTML = `Hello, <slot>world</slot>!`
  }});
````

**Comment by jhuddle** [comment]
Hello Danny,

Thanks very much for pointing out the omission of `super()` in my example custom element class; much appreciated, and I've updated the documentation forthwith.

What goes substantially less appreciated, however, is the pompous, condescending tone in which you file this non-issue. **Any developer that had some _social_ education** would have simply written:

> Your example code is not working; it seems you're missing a call to `super()`?

And any developer who would claim that forcing the DOM parser to re-evaluate the content string for every component instance is somehow more educated - or who implies that writing a one-liner to that effect would be of greater merit _as example code_ - is not worthy of further attention from this project. Issue closed.
