### ISSUE TITLE
`import` from within a template's script

### ISSUE THREAD

**Issue by BlueNebulaDev** [jhuddle/ponys#4]
I'd need to `import` something from a local module in order to implement a custom element.

Something like:

```html
<template name="xxx-yyy">
  <script>
    import XElement from './x.js';
    export default class extends XElement {
    }
  </script>
</template>
```

but it fails with:

> TypeError: Failed to resolve module specifier "./x.js". Invalid relative url or base scheme isn't hierarchical.

It seems like the problem is that [you can't import relative paths from within a script imported via a data URL](https://stackoverflow.com/q/69080288/13948744).

How would you suggest to handle this using Ponys?

**Comment by jhuddle** [comment]
Hi @BlueNebulaDev, thanks for posting the issue - I'll look into it, and will get back to you with my best attempt at a fix or a workaround. My initial thought is to try respecifying the path to the local module using `import.meta.resolve()`, but I don't yet see a way to get this to work for more deeply nested relative imports; it may be that no better outcome is possible before the browsers implement HTML modules. In any case, I'll see what I can do; if you have any ideas, please let me know! :slightly_smiling_face:

**Comment by BlueNebulaDev** [comment]
I'm short of ideas. The only working solutions I can think of is to pre-process the file. But that seems quite against the philosophy of Ponys.

Are JS modules finalized? I believe it might be worth bringing up this issue with the committee working on them. The clean solution would be for dynamic `import` to accept as a parameter its own URL (`import("data:...", {url:"."})`)...

**Comment by jhuddle** [comment]
Hi @BlueNebulaDev, I think I figured out a solution to this issue: using the [`URL` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), I was able to reliably rewrite any [relative import paths](https://developer.mozilla.org/en-US/docs/Web/API/URL_API/Resolving_relative_references) found during parsing of the component setup script as absolute URLs, with respect to both `location.origin` and the location of the component class.

Hopefully that's fixed it; please do let me know if you encounter any further unexpected behavior. Thanks again for raising the issue! :slightly_smiling_face:
