### ISSUE TITLE
Need something to specify which script tag to use when calling import

### ISSUE THREAD

**Issue by mwebb-bzs** [jhuddle/ponys#5]
When there are two or more script tags in an external HTML file, there should be a way to designate which one should be used by Ponys.

I am running into this using Vite, but I am thinking this may not be only reason why there may be more than one `<script>` tag in an HTML file pulled in with `Ponys.import`.

Vite apparently injects an additional `<script>` tag at the top of the imported HTML content. Since the current code just gets the first script in the document, it's grabbing this injected script tag and ignoring my script tag with the exported element.

Would you be able to add an option or some way to specify which script tag should be used when importing from an external HTML file using `Ponys.import`?

**Comment by jhuddle** [comment]
Hi @mwebb-bzs, thanks for submitting the issue.

I've changed the parsing of imported components such that the first `<script>` tag found containing a `setup` attribute (e.g. `<script setup>`) will now take priority over any other script tag - hopefully including the one injected by Vite.

And to make it even more explicit in future releases, non-`setup` tags should now be considered deprecated, and will not be used by Ponys to generate components from v0.4.0 onwards.

Hopefully that should do the trick! Best of luck with it - any further issues, do let me know. :slightly_smiling_face:

**Comment by mwebb-bzs** [comment]
This is awesome! Thanks @jhuddle.
