### ISSUE TITLE
Bug in Safari breaks Ponys

### ISSUE THREAD

**Issue by faggion** [jhuddle/ponys#6]
Hi, first of all, nice job done here!

Looks like some still used Safari versions doesn't support (by a bug) the regex used in Ponys script.

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by jhuddle** [comment]
Hello @faggion, thanks for the kind greeting and the valuable feedback! I've now removed the lookbehind from the regex in question; hopefully Safari will let me put it back some day :)
